# Generated by Django 3.0.7 on 2020-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200624_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
