# Generated by Django 3.0.7 on 2020-06-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200624_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
