# Generated by Django 3.0.7 on 2020-06-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200624_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='backend',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='backend.Backend'),
        ),
    ]
